// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "./types.ts";

export const MODELS = {
	"noumena": {
		"kimi-2.7-coder": {
			"id": "kimi-2.7-coder",
			"name": "Kimi 2.7 Coder",
			"requestModel": "/data/models/hf/moonshotai__Kimi-K2.7-Code",
			"api": "openai-completions",
			"provider": "noumena",
			"baseUrl": "https://api.noumena.com/v1",
			"headers": {
				"x-app": "cli",
				"anthropic-beta": "oauth-2025-04-20",
			},
			"compat": {
				"supportsDeveloperRole": false,
				"supportsStore": false,
				"supportsUsageInStreaming": true,
				"supportsReasoningEffort": true,
				"maxTokensField": "max_tokens",
				"thinkingFormat": "noumena",
			},
			"reasoning": true,
			"thinkingLevelMap": {
				"off": "none",
				"minimal": null,
				"low": "medium",
				"medium": "medium",
				"high": "high",
				"xhigh": null,
			},
			"input": ["text"],
			"cost": {
				"input": 0,
				"output": 0,
				"cacheRead": 0,
				"cacheWrite": 0,
			},
			"contextWindow": 200000,
			"maxTokens": 256000,
		} satisfies Model<"openai-completions">,
	},
} as const;
