import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Model, OpenAICompletionsCompat } from "../src/types.ts";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, "..");

const NOUMENA_BASE_URL = "https://api.noumena.com/v1";
const NOUMENA_KIMI_2_7_CODER_MODEL = "/data/models/hf/moonshotai__Kimi-K2.7-Code";
const NOUMENA_OAUTH_BETA_HEADER = "oauth-2025-04-20";

const NOUMENA_KIMI_2_7_CODER_COMPAT: OpenAICompletionsCompat = {
	supportsDeveloperRole: false,
	supportsStore: false,
	supportsUsageInStreaming: true,
	supportsReasoningEffort: true,
	maxTokensField: "max_tokens",
	thinkingFormat: "noumena",
};

const MODELS = {
	noumena: {
		"kimi-2.7-coder": {
			id: "kimi-2.7-coder",
			name: "Kimi 2.7 Coder",
			requestModel: NOUMENA_KIMI_2_7_CODER_MODEL,
			api: "openai-completions",
			provider: "noumena",
			baseUrl: NOUMENA_BASE_URL,
			headers: {
				"x-app": "cli",
				"anthropic-beta": NOUMENA_OAUTH_BETA_HEADER,
			},
			compat: NOUMENA_KIMI_2_7_CODER_COMPAT,
			reasoning: true,
			thinkingLevelMap: {
				off: "none",
				minimal: null,
				low: "medium",
				medium: "medium",
				high: "high",
				xhigh: null,
			},
			input: ["text"],
			cost: {
				input: 0,
				output: 0,
				cacheRead: 0,
				cacheWrite: 0,
			},
			contextWindow: 200000,
			maxTokens: 256000,
		} satisfies Model<"openai-completions">,
	},
} as const;

function stringifyValue(value: unknown, indent = "\t"): string {
	if (Array.isArray(value)) {
		return `[${value.map((item) => stringifyValue(item, indent)).join(", ")}]`;
	}
	if (value && typeof value === "object") {
		const lines = Object.entries(value)
			.map(([key, entry]) => `${indent}${JSON.stringify(key)}: ${stringifyValue(entry, `${indent}\t`)},`)
			.join("\n");
		return `{\n${lines}\n${indent.slice(1)}}`;
	}
	return JSON.stringify(value);
}

function generateModelsFile(): string {
	let output = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "./types.ts";

export const MODELS = {
`;

	for (const [providerId, models] of Object.entries(MODELS)) {
		output += `\t${JSON.stringify(providerId)}: {\n`;
		for (const [modelId, model] of Object.entries(models)) {
			output += `\t\t${JSON.stringify(modelId)}: ${stringifyValue(model, "\t\t\t")} satisfies Model<"${model.api}">,\n`;
		}
		output += "\t},\n";
	}

	output += "} as const;\n";
	return output;
}

writeFileSync(join(packageRoot, "src/models.generated.ts"), generateModelsFile());
console.log("Generated src/models.generated.ts with 1 Noumena model.");
