import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(scriptDir, "..");

const output = `// This file is auto-generated by scripts/generate-image-models.ts
// Do not edit manually - run 'npm run generate-image-models' to update

import type { ImagesApi, ImagesModel } from "./types.ts";

export const IMAGE_MODELS = {} as const satisfies Record<string, Record<string, ImagesModel<ImagesApi>>>;
`;

writeFileSync(join(packageRoot, "src/image-models.generated.ts"), output);
console.log("Generated src/image-models.generated.ts with no built-in image models.");
